# Until all the dependencies move to android X
android.useAndroidX = true
android.enableJetifier = true
org.gradle.parallel=true
android.nonTransitiveRClass = false
#org.gradle.warning.mode=none
org.gradle.warning.mode=all

org.gradle.jvmargs=-Xms2g -Xmx4g

ANDROID_X_VERSION=1+

GRADLE_CLASS_PATH=com.android.tools.build:gradle:3.5.1

PROTOBUF_CLASS_PATH=com.google.protobuf:protobuf-gradle-plugin:0.9.4
PROTOBUF_DEPENDENCY=com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7

BUILD_TOOLS_VERSION=30.0.3
COMPILE_SDK=android-S
KOTLIN_CLASS_PATH=org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0
KOTLIN_VERSION=1.7.10
KTX_VERSION=2.4.0-alpha03
COROUTINES_VERSION=1.6.4

